### ISSUE TITLE
Users cannot see system information when logged in

### ISSUE THREAD

**Issue by MrTimbones** [openenergymonitor/heatpumpmonitor.org#33]
> I seem to have an issue where when I am logged into Heatpumpmonitor the summary information for all the systems does not show up (all the fields are blank). As soon as I log out, all the information appears.

https://community.openenergymonitor.org/t/heatpumpmonitor-missing-system-summaries/25531

**Comment by TrystanLea** [comment]
This is now fixed I think?

**Comment by MrTimbones** [comment]
Seems to still be an issue, though it doesn't affect admins.

**Comment by TrystanLea** [comment]
This should be fixed now, testing here logged in as a non admin user seems to work fine?
