### ISSUE TITLE
Cost explorer

### ISSUE THREAD

**Issue by TrystanLea** [openenergymonitor/heatpumpmonitor.org#48]
Explore cost implication for each system on different tariffs e.g: user entered unit rate, price cap or average rate and half hourly tariffs: Octopus Agile, Cosy & Go.

**Comment by zarch1972** [comment]
For anyone on Octopus tariffs you could go mega deep on this.
Ask for their API code and pull their last 30 days average unit price from Octopus API/Graphql?

I think i've put my unit price at 14p on the information as that was my winter average.  But as we get more solar that will no doubt go down month to month.  And that doesn't include the solar contribution.

Cost is going to be really hard to nail down.

Not sure any of that helped.

**Comment by TrystanLea** [comment]
Thanks Mick, thinking of keeping it one layer up from that I think. Pull in the cosy, go, agile rates for a particular region (one that has central enough costs) and then apply those half hourly prices to all systems as a way to ask a what if question.. E.g what if every heat pump on the list was on Cosy or Go or Agile. 

The obvious issue with this is that this will not be able to account for demand shifting that the user might undertake if they were actually on a particular tariff.. but it's probably the best we can do without getting super complicated..

**Comment by TrystanLea** [comment]
First stage cost explorer now complete:

https://heatpumpmonitor.org/#mode=costs&tariff=agile

![image](https://github.com/openenergymonitor/heatpumpmonitor.org/assets/503186/61b2671e-30b7-458b-b2a8-07d32de10987)

Option to explore:

- Price cap
- OVO Heat pump plus
- Octopus Agile
- Octopus Cosy
- Octopus GO
- User entered 

It would be great to add Octopus GO Intelligent of course.

I think an option to provide a whole house import feed might be a good idea enabling automatic actual import cost analysis. This could allow both cost at heat pump calculation and cost at import (e.g after battery & EV lowering of average with low cost charging) comparisons.. 

Ultimately we should really include levelised cost of storage and onsite generation for true comparison, which gets a lot more complicated.. It would be great to produce some worked examples that include all costs including upfront installation costs..
